### ISSUE TITLE
GHA: 205-dynamic-tabs-compat: Test failing with cosmo4 theme

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#126]
This test started failing since March 17, 2021. Could be due to https://github.com/rstudio/bslib/commit/df10a878e0e9d1e42c83b4c2101bc8d9f00ad314

Failing on all OS and R versions

Tab panel title shown on the right instead of left

OLD snapshot:
<img width="912" alt="205-dynamic-tabs-compat-OLD" src="https://user-images.githubusercontent.com/5369655/111833897-0be34f00-88b0-11eb-84e4-6b1a836caf2b.png">

NEW snapshot:
<img width="913" alt="205-dynamic-tabs-compat-new" src="https://user-images.githubusercontent.com/5369655/111833915-1271c680-88b0-11eb-9c2d-508ee87f1ebf.png">

Other png diffs:
<img width="913" alt="205-dynamic-tabs-compat-other-diffs" src="https://user-images.githubusercontent.com/5369655/111833947-1d2c5b80-88b0-11eb-8b90-f005fe2b6ef7.png">

**Comment by MadhulikaTanuboddi** [comment]
March 25 test results review:

Previous Tab panel title seems to be fixed.

Now, Test failing at the navlistPanel() controls section. Infact, the comparison of old and new snapshots in this case does not make sense at all. OLD is looking at the second tabPanel with name "0" and NEW is looking at the first tabPanel with name "Base tab"

Check the old and new snapshots.

OLD:
<img width="1065" alt="March-25-205-dynamic-tabs-compat-cosmo4-OLD" src="https://user-images.githubusercontent.com/5369655/112529186-3b87d080-8d62-11eb-8a53-f3627ea6303a.png">

NEW
<img width="1064" alt="March-25-205-dynamic-tabs-compat-cosmo4-new" src="https://user-images.githubusercontent.com/5369655/112529209-42164800-8d62-11eb-813f-034eca4b7197.png">

@cpsievert : can you please double check this?

**Comment by cpsievert** [comment]
Seems this is a real thing we'll need to fix in Shiny
