### ISSUE TITLE
GHA: Typescript related: shinyjster test failures on few apps

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#152]
The following apps has been showing shinyjster test failures since June 16, 2021. Refer to https://connect.rstudioservices.com/connect/#/apps/4234/access

- [ ] **140-selectize-inputs**

    runApp('apps/140-selectize-inputs')

Listening on http://127.0.0.1:6862
shinyjster - Progress: 1/141 (waiting)
shinyjster - Progress: 1/141 (running)
shinyjster - Progress: 2/141 (waiting)
shinyjster - Progress: 2/141 (running)
shinyjster - Progress: 3/141 (waiting)
shinyjster - Progress: 4/141 (waiting)
shinyjster - Progress: 4/141 (running)
shinyjster - Progress: 5/141 (waiting)
shinyjster - Progress: 5/141 (running) - Error found: [] does not equal [ { label: '1', valu...
Warning: Error in cat: argument 6 (type 'list') cannot be handled by 'cat'
  1: runApp
shinyjster - Browser window has been closed. Stopping Shiny Application now.
$type
[1] "error"

$error
$error$message
[1] "[] does not equal [ { label: '1', valu..."

$error$x
list()

$error$y
$error$y[[1]]
$error$y[[1]]$label
[1] "1"

$error$y[[1]]$value
[1] "1"

$error$y[[2]]
$error$y[[2]]$label
[1] "2"

$error$y[[2]]$value
[1] "2"

$error$xStr
[1] "[]"

$error$yStr
[1] "[ { label: '1', value: '1' }, { label: '2', value: '2' } ]"
      
         
- [ ] **163-select-factor**

        shiny::runApp('apps/163-select-factor')
     Loading required package: shiny

Listening on http://127.0.0.1:6973
shinyjster - Progress: 1/160 (waiting)
shinyjster - Progress: 1/160 (running)
shinyjster - Progress: 2/160 (waiting)
shinyjster - Progress: 3/160 (waiting)
shinyjster - Progress: 3/160 (running)
shinyjster - Progress: 4/160 (waiting)
shinyjster - Progress: 4/160 (running) - Error found: 0 does not equal 26
shinyjster - JS error found! Error:
	msg: 0 does not equal 26
	x: 0
	y: 26
	xStr: 0
	yStr: 26
	contextStr: { values: [] }
shinyjster - Error found! Closing Browser window

- [ ] **900-text-jster**

 runApp('apps/900-text-jster')

Listening on http://127.0.0.1:6973
shinyjster - Progress: 1/23 (waiting)
shinyjster - Progress: 1/23 (running)
shinyjster - Progress: 2/23 (waiting)
shinyjster - Progress: 3/23 (waiting)
shinyjster - Progress: 3/23 (running)
shinyjster - Progress: 4/23 (waiting)
shinyjster - Progress: 5/23 (waiting)
shinyjster - Progress: 5/23 (running)
shinyjster - Progress: 6/23 (waiting)
shinyjster - Progress: 6/23 (running) - Error found: Cannot read property 'click' of undefined
shinyjster - JS error found! Error:
	 Named list()
shinyjster - Error found! Closing Browser window

- [ ] **212-shinymeta**

 runApp('apps/212-shinymeta')
Welcome to clipr. See ?write_clip for advisories on writing to the clipboard in R.

Listening on http://127.0.0.1:6973
shinyjster - Progress: 1/11 (waiting)
shinyjster - Progress: 1/11 (running)
shinyjster - Progress: 2/11 (waiting)
shinyjster - Progress: 3/11 (waiting)
shinyjster - Progress: 3/11 (running)
shinyjster - Progress: 4/11 (waiting)
shinyjster - Progress: 4/11 (running) - Error found: Cannot read property 'click' of undefined
shinyjster - JS error found! Error:
	 Named list()
shinyjster - Error found! Closing Browser window

Note: I am still reviewing few more test results and will add any more failures related to TS/shinyjster here

**Comment by schloerke** [comment]
140 & 163 are due to shinyjster not finding the selectize options. The selectize code was updated in https://github.com/rstudio/shiny/pull/3413/files (a few days ago by JJ) to prevent clipping. Shinyjster needs to now search for `$("body .selectize-dropdown:visible .selectize-dropdown-content").children()` instead.

**Comment by schloerke** [comment]
All apps were related to selectize and not being able to properly retrieve the possible options.

Fixed in https://github.com/schloerke/shinyjster/commit/541f4b3b6905ac836db0ef276cda05832f6bb661#diff-68eee7276970badb765759baada80f9a389333edb361b0a68a275f9003c8a59dR12-R16

**Comment by cpsievert** [comment]
I think these are fixed now?
