### ISSUE TITLE
GHA: Apps using "DT::renderTable" failing

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#164]
Following apps using the `DT::renderTable` function are failing and throwing the following error

```
> runApp('apps/018-datatable-options')
Listening on http://127.0.0.1:3574
Warning: Error in missing: invalid use of 'missing'
  52: eval
  51: eval
  50: getQuosure3
  49: shiny::exprToFunction
  48: DT::renderDataTable
  47: server [/Users/madhulika/Documents/shinycoreciapps_NEW/shinycoreci-apps/apps/018-datatable-options/server.R#4]
Error in missing(TRUE) : invalid use of 'missing'
```

- [ ] 063-superzip-example
- [ ] 095-plot-interaction-advanced
- [ ] 012-datatables
- [ ] 021-selectize-plot
- [ ] 018-datatable-options

<img width="1546" alt="DT_tables_runs" src="https://user-images.githubusercontent.com/5369655/125993453-2d1c5e67-d6e7-477b-8ae0-423d52386bc1.png">

Introduced by https://github.com/rstudio/shiny/commit/3f48e3b0af91a211b7a819df34e909b5f829f77f

**Comment by wch** [comment]
This should be fixed by https://github.com/rstudio/shiny/pull/3466.

**Comment by MadhulikaTanuboddi** [comment]
This fix https://github.com/rstudio/shiny/pull/3466 probably needs to be reverted due to https://github.com/rstudio/shinycoreci-apps/issues/165. Reopening the original issue for now.

**Comment by schloerke** [comment]
Closed via https://github.com/rstudio/shiny/pull/3468
