### ISSUE TITLE
GHA: shinyjster test failures due to "quosure" changes

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#165]
shinyjster tests on apps started failing in the build https://github.com/rstudio/shinycoreci-apps/actions/runs/1044434863

https://github.com/rstudio/shinycoreci-apps/runs/3101893859?check_suite_focus=true#step:32:296

local repro example when running shinyjster test..

```
> runApp('apps/001-hello')
Listening on http://127.0.0.1:3717
Warning: Error in eval_tidy: object 'input' not found
  1: runApp
Warning: Error in eval_tidy: object 'input' not found
  1: runApp
Warning: Error in eval_tidy: object 'input' not found
  1: runApp
Warning: Error in jster_message: could not find function "jster_message"
  38: callback
```

This is caused due to https://github.com/rstudio/shiny/pull/3466

**Comment by schloerke** [comment]
Closed via https://github.com/rstudio/shiny/pull/3468
