### ISSUE TITLE
GHA: `026-shiny-inline` test failures with rendering bold text

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#199]
https://github.com/rstudio/shinycoreci-apps/tree/main/apps/026-shiny-inline app does not render the bolded text correctly since the change with https://github.com/rstudio/htmltools/commit/72cc41ef38c587e34d130045451ea95e0ef851dc.

Shinytest tests were failing due to the same.

<img width="1541" alt="026-shiny-inline-htmltools-bold-text" src="https://user-images.githubusercontent.com/5369655/146988616-58f3d9de-d379-4d12-a8ca-572652bb2d4b.png">

**Comment by MadhulikaTanuboddi** [comment]
Should be fixed by https://github.com/rstudio/htmltools/pull/308

**Comment by MadhulikaTanuboddi** [comment]
Verified on 12/21- Not fixed yet. checking with Carson

**Comment by cpsievert** [comment]
Thanks @MadhulikaTanuboddi, looks like rstudio/htmltools#308 fixed the issue for _statically_ rendered inline code blocks, but looks like Shiny will need a change to fix it for _dynamically_ rendered ones

**Comment by cpsievert** [comment]
Let's track this issue via https://github.com/rstudio/shiny/issues/3568 instead of here.

(I'll update the Trello card to point to the Shiny issue/PR)
