### ISSUE TITLE
Github Actions: New workflow to run specific tests that are added/modified from a PR

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#79]
Barret and I had this conversation briefly.

Currently, when a PR is created to add additional tests to shinycoreci-apps, github actions would run all the tests. Usually a test run would take ~4-7 hrs. 

Few examples:
1. https://github.com/rstudio/shinycoreci-apps/actions/runs/294252093
2. https://github.com/rstudio/shinycoreci-apps/actions/runs/291666831
3. https://github.com/rstudio/shinycoreci-apps/actions/runs/282465491

I was thinking it would be helpful to have a new workflow that should run "only" the tests involved within a PR. For example, if any new tests are added to `apps` or any modifications made to a set of existing tests. This would 

-> Yield immediate and clear results in github actions to review by the shiny-core team. Saves time instead of waiting for hours to make the decision about merging a specific PR. Helps QA team to narrow down the test results and report to the team.

My assumption is that usually any other apps that are not modified (group A) wont be impacted with changes in the apps modified/added (group B).

Inputs, suggestions, comments are welcome on this request.

cc: @schloerke

**Comment by cpsievert** [comment]
Pretty sure this has been addressed?
