### ISSUE TITLE
Github Actions: 194-plot-cache-key test failing at reactlog 

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#83]
Steps:
1. Run `194-plot-cache-key` shiny app using shinytest
2. The test is failing for past few days due to a new output event being displayed

Old result snapshot:
<img width="1003" alt="Old_194-plot-cache-key" src="https://user-images.githubusercontent.com/5369655/99698797-0f6fe200-2a46-11eb-93ed-0d0f356fbd43.png">

New result snapshot:
<img width="1279" alt="New-194-plot-cache-key" src="https://user-images.githubusercontent.com/5369655/99698865-231b4880-2a46-11eb-826f-9d3602d86bb3.png">

Ref: https://github.com/rstudio/shinycoreci-apps/runs/1416965207?check_suite_focus=true

**Comment by MadhulikaTanuboddi** [comment]
This test is still failing (with a different set of reactlog differences). Here are the old and new snapshots from shinytest. Please let me know if you need more details.

OLD:
<img width="1125" alt="194-plot-cache-key-old-snapshot" src="https://user-images.githubusercontent.com/5369655/100896587-9fb11c80-3473-11eb-92c6-061e230ac928.png">

NEW:
![Uploading 194-plot-cache-key-new-snapshot.png…]()

**Comment by wch** [comment]
Thanks, I think we have a fix for it now!

**Comment by MadhulikaTanuboddi** [comment]
Here is the latest expected dependency graph approved by Winston:

![194-plot-cache-key-reactlog-dependency-graph-Dec 4](https://user-images.githubusercontent.com/5369655/101209739-1fccb300-3629-11eb-93f2-dc29c481d9e0.png)

Helpful notes from Barret:

_The extra observeEventHandler is not added to the reactlog anymore
And the observer previously labelled observeEvent({ eval_tidy(qs) }) has a better label now_

_The original bad label was fixed in_ https://github.com/rstudio/shiny/pull/3160
_The extra/white reactives was fixed in_ https://github.com/rstudio/shiny/pull/3177
_The random reactiveVal with value 0_ was fixed in https://github.com/rstudio/shiny/pull/3180

**Comment by MadhulikaTanuboddi** [comment]
Will close this issue once we update the expected snapshots in different branches and make sure when the test passes in GHA

**Comment by MadhulikaTanuboddi** [comment]
Verified. Ref: https://trello.com/c/pRfzaNmb/521-app-194-plot-cache-key-fix-labels-with-bindevent
