### ISSUE TITLE
Github Actions: 157-date-format test failure

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#85]
This test has been consistently failing on **Mac: 4.0** and **Ubuntu-18: 4.0** runs. 
Remaining 10 runs  (Mac, Windows, Ubuntu with other versions of R) looks good with this test.

I am able to repro this locally on Mac with 4.0.

Steps:
1. Install the latest of shinycoreci -> remotes::install_github("rstudio/shinycoreci")
2. Set your RStudio IDE working directory to https://github.com/rstudio/shinycoreci-apps/tree/master/apps
3. Run the app `157-date-format` using `shiny::runApp(apps/157-date-format)` or `shinyjster::run_jster('apps/157-date-format')`

Expected: App should show 14 warnings
Actual: On Mac, the shinyjster test fails showing only 13 warnings. The test works on Windows. 

```
> shinyjster::run_jster('apps/157-date-format')

Listening on http://127.0.0.1:8000
Warning: Couldn't coerce the `value` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `max` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `start` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `end` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `min` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `max` argument to a date string with format yyyy-mm-dd
shinyjster - Progress: 1/2 (waiting)
shinyjster - Progress: 1/2 (running)
shinyjster - Progress: 2/2 (waiting)
shinyjster - Progress: 2/2 (running) - Error found: false does not equal true
shinyjster - JS error found! Error:
	msg: false does not equal true
	x: FALSE
	y: TRUE
	xStr: false
	yStr: true
	yStr: true
shinyjster - Error found! Closing Browser window
shinyjster - Browser window has been closed. Stopping Shiny Application now.
# A tibble: 1 x 3
  appDir               successful returnValue     
  <chr>                <lgl>      <list>          
1 apps/157-date-format FALSE      <named list [2]>
```

![app-157-shinyjster-testresult](https://user-images.githubusercontent.com/5369655/99861829-74156480-2b4c-11eb-80ec-73b79d1a4275.png)
![app-157-shinyjster-warnings-expected-14](https://user-images.githubusercontent.com/5369655/99861831-77a8eb80-2b4c-11eb-8d80-4fa47819a457.png)

Note: Barret helped me with some debugging. It looks like the warming message `catchWarning(dateInput, "x2", "Mis-specified `min`", min = ""),` is not printed. Not sure if this makes sense -> when I added a empty string to min i.e `min=" "`, the warning is printed

Could this be due to https://github.com/rstudio/shiny/issues/2591?

**Comment by cpsievert** [comment]
I think this should be fixed now (please reopen if not)

**Comment by MadhulikaTanuboddi** [comment]
Verifed and looks good. Thank you @cpsievert 

![Uploading 157-date-format-test-result-after-fix.png…]()
