### ISSUE TITLE
Automatically deploy apps with a workflow

### ISSUE THREAD

**Issue by wch** [rstudio/shinycoreci-apps#9]
The test apps should be automatically deployed to:

* Connect
* shinyapps.io, 
* A server running SSO (or maybe Docker container?)
* A server running SSP (or Docker container)

Then the shinyjster tests should be run using each of the platforms. It's possible that the SSO and SSP Docker containers could be run on the Github actions machines.

**Comment by schloerke** [comment]
* SSO / SSP Docker files: https://github.com/rstudio/shinycoreci-apps/pull/20
* Shinyapps.io / Connect: https://github.com/rstudio/shinycoreci-apps/pull/18
